export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Experience } from "./Experience";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Nav } from "./Nav";
export { default as Portfolio } from "./Portfolio";
export { default as Services } from "./Services";
export { default as Testimonials } from "./Testimonials";
